import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { FontDebugger } from "./components/FontDebugger";

const inter = Inter({
  variable: "--base-type-font-family-body",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--base-type-font-family-headings",
  weight: ["300", "400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${merriweather.variable} antialiased`}
      >
        <FontDebugger />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
